### ISSUE TITLE
Install on greebo gives "500 server unavailable"

### ISSUE THREAD

**Issue by bactram** [JovinJovinsson/dokuwiki-plugin-navbox#3]
When I installed navbox on my greebo (2018-04-22a), it returned with a "500 server unavailable" error. This error persisted when I tried to load other pages (like the main page). The error went away when I removed the dokuwiki/lib/plugins/navbox directory. As is, this plugin breaks the website. Looking forward to using it when it's fixed.

**Comment by JovinJovinsson** [comment]
Hey @bactram I'll have a look into this shortly. It may be the way that the Advanced Tags function works and I may need to temporarily create a Greebo version before bringing this capability forward.

**Comment by JovinJovinsson** [comment]
Hey @bactram, I'm running Greebo over at https://openwiki.midgardapps.com and can't verify the issue.

Are your folder permissions correct? Folders should be 755 or 775 and files should be 644.

Also how did you install? Extract to the directory? Through Search and Install? or Manual Install?

**Comment by bactram** [comment]
It looks like my folder permissions are OK. The folders are 755.

I'm installing via Search and Install.

I'm getting a syntax error on syntax.php line 244. It looks like there's a missing close paren on line 243.
When I fix that, I get an unexpeced 'new' on line 322 of syntax.php. I don't know enough PHP to know what's wrong there.

**Comment by JovinJovinsson** [comment]
I checked it out - turns out my Wiki didn't actually update appropriately! I also experienced the 500 error. I found that pesky missing ')' and the unexpected new was actually due to an issue I thought I stomped, but obviously forgot - PHP 5.6 is okay with the code '& new' but PHP 7.0 is not, I've removed the '&' and it all works on my wiki.

Can you confirm?

**Comment by bactram** [comment]
Looks good now. Thanks.
