### ISSUE TITLE
Error Navbox with my Dokuwiki

### ISSUE THREAD

**Issue by Thimmy74** [JovinJovinsson/dokuwiki-plugin-navbox#7]
**Describe the bug**
Pages using the "Navbox" plugin are completely broken. There is a big error message (see photo below) moreover it is the only plugin which bug with my site since the update to the last version. However, I tried to modify the "syntax.php" page as you suggested on another post, but nothing to do.

**To Reproduce**
1. Update to Version: 2020-07-29 "Hogfather"
2. Download latest version of the "Navbox" plugin
3. Modify the "syntax.php" file with the information found on its pages

**Expected behavior**
Before the update I had used this plugin on 3 pages to display a wikipedia-style "navbox", so I know it's because of this update that the plugin doesn't work anymore.

**Screenshots**
[https://cdn.discordapp.com/attachments/368370940851257344/755177011873448036/unknown.png](url)
[https://i.goopics.net/A9qXa.png](url)

**Client Information:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Browser Version: 85.0.4183.102

**Host Information:**
 - DokuWiki Version: 2020-07-29 "Hogfather"
 - PHP Version: 5.6

**Comment by JovinJovinsson** [comment]
@Thimmy74 going to close this as I'm revitalising the efforts on this, and there have been some merge requests completed.
Please let me know if this is still happening.
